### ISSUE TITLE
How to put together?

### ISSUE THREAD

**Issue by Viovyx** [Lixulia/Arcturus#1]
Is there any guide on how the components should be put together in the case? I have bought all the components that are listed as compatible with the Arturus case and I have also 3d printed all the main cases and extensions that I need for my SlimeVR setup.

**Comment by Lixulia** [comment]
https://photos.app.goo.gl/i6C6iSW95ACs4k7F7

Battery in the big slot, type c in the middle, d1 to the far left, and switch in the side wall hole. The bmi goes in the rectangle slot
