### ISSUE TITLE
My adventure with this case

### ISSUE THREAD

**Issue by S-y-c-h-o** [Lixulia/Arcturus#3]
I have done alot of work with this case, specifically modifying it to meet my individual needs. Such as:

Enlarged / moved port holes
Added hole for JST female port
Removed hole for extension wires
Reinforced case next to JST hole as case snapped on multiple occasions
Switch hole enlarged
Riser added to back of microcontroller spot
Indent added to front microcontroller spot
Raised 'walls' next to microcontroller so that the previous two edits don't make the microcontroller sit above the 'walls'
^ (These allow the microcontroller to sit flat and snap in
The lid's dovetail is not the same on both sides. ?
Lid's details were creating strange toolpaths, made them far thinner and removed through-hole
Dovetail on case too thin and broke easily (it was less than .2 mm thick on multiple layers), enlarged by 1mm on both sides
Dovetail lid modified to cooperate with previous edit
Removed lid supports on case

A number of these edits were personal preferance, but i think that some may be implemented into the case for all users. I can send a copy of the edited case if desired.
Note: I have had to compensate for my printer's relatively poor accuracy, and many of these edits may not have been needed to be made if the printer did not necessitate a part with larger tolerances.
Also note: first time posting on github and also 3d printing. i claim to be no expert. pls go easy on me.

**Comment by Lixulia** [comment]
Hello! You can post your own versions and edits online, Idc. This is a public case that I made for public use. Im temporarily giving up on fixing every little thing people complain about, and who knows, maybe someday ill come back and fix it. For now, Im just gonna upload the fusion files so people can do whatever. Have fun! closing this now.
